No std support
frisitano/merkle-tree-db pull request #30
Opened 2023-05-19 10:53 UTC by Ankitwasnik

PR for [Issue](https://github.com/frisitano/merkle-tree-db/issues/9)

Solution:
1. lib.rs contain declarations which get toggled based on the std and no_std compatibility.
2. Node and NodeHash fmt method will work only for std modules.

2023-05-19 11:37 UTC, frisitano reviewed
Thank you for this @Ankitwasnik! I was thinking that maybe we should update [ci](https://github.com/frisitano/merkle-tree-db/blob/master/.github/workflows/ci.yml) to include checks and test in `no_std` environment.  What do you think?  [Here](https://github.com/0xPolygonMiden/miden-vm/blob/main/.github/workflows/ci.yml) is some inspiration for how it could be implemented.

2023-05-19 11:49 UTC, Ankitwasnik commented
Agree @frisitano , I will update the PR.

2023-05-22 05:33 UTC, frisitano requested changes
Looks good!  I think we should change usage of `crate::*` to `super::*` to be consistent with the rest of the imports used in this library.  What do you think?

2023-05-22 05:33 UTC, frisitano commented on src/error.rs
> +use crate::rstd::{string::String, vec::Vec};
I think we should use `use super::rstd::{string::String, vec::Vec};` instead here.

2023-05-22 05:33 UTC, frisitano commented on src/indexdb.rs
> +use crate::rstd::vec::Vec;
Similarly use `use super::rstd::vec::Vec;` and everywhere else in this PR.

2023-05-22 05:53 UTC, Ankitwasnik commented on src/indexdb.rs
> +use crate::rstd::vec::Vec;
Done

2023-05-22 05:54 UTC, Ankitwasnik commented on src/error.rs
> +use crate::rstd::{string::String, vec::Vec};
Done

2023-05-22 05:59 UTC, frisitano requested changes
Could you merge all imports from `super` please?

2023-05-22 05:59 UTC, frisitano commented on src/indexdbmut.rs
>  use super::{
Can you merge all imports from the super namespace for this PR please.  This would become:

```rust
use super::{
    DBValue, HashDB, Hasher, IndexTreeMut, Key, KeyedTreeMut, TreeDBMut, TreeDBMutBuilder,
    TreeError, TreeRecorder, rstd::vec::Vec
};
```

2023-05-22 11:26 UTC, frisitano requested changes
This looks great! Thanks a lot for your contribution.  The code is ready to merge.  One final thing, could you please rebase and squash your commits into a single commit please.  This will help us keep commit history clean on the main branch.  After that we are ready to merge.

2023-05-23 05:54 UTC, frisitano approved these changes
Looks good thank you!  Lets get this merged.

2023-05-23 06:05 UTC, Ankitwasnik commented
> Looks good thank you! Lets get this merged.

Thanks. Merging this PR.

2023-05-23 06:10 UTC, merged